from .evaluador.evaluador import evaluador_blueprint
from .examen.exament_route import examen_blueprint
from .resultado_aprendizaje.resultado_aprendizaje_route import resultado_aprendizaje_blueprint


